### ISSUE TITLE
Feature: User can Add cards to their deck to make the deck that they want

### ISSUE THREAD

**Issue by edc061598** [edc061598/front-end-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Display the api for the card or card(s) that you want to use, depending on what was searched on the homepage. 
- [ ] Have a click event for the add button on the lower or upper right-hand corner to add cards to your deck 
- [ ] have another click event for a button called "update card strategies" that will allow the user to update to the card they want
- [ ] Create a click event listener for the cards that you would like to add to your deck before clicking on the add button(ask instructor for insight)
- [ ] Once the cards have been selected to add, the add button will redirect you to the view where your deck will be
- [ ] create a "ToggleNoentries" function that will display, 'NO CARDS IN YOUR DECK' when the input in local storage is empty 
- [ ] create a 'viewSwap' function that will represent the name of the view that you would want to see, depending on which button you press
