### ISSUE TITLE
Feature: User can change(update) the cards in their deck. They can specify how many of each card do they need. Edit the cards so they know which cards they’ll need as well as how much. Add text to how they can play their cards.

### ISSUE THREAD

**Issue by edc061598** [edc061598/front-end-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] #4
   - [ ]the viewswap function will show the form  
   - the drop down menus can be chosen again for blue eyes or dark magician 
   - the api can be specified for one singular card or a range of cards again, which will be unordered lists    
   - the values of the api will be updated with the new values given from 'Update Card Strategies' 
   - [ ] populate the entry form with the clicked entry's values from the object stored in the `data.editing` property.
   - [ ] Change the title to 'Card Strategy' above the picture 
-[ ] assign a new entry id from data.editing to the new object with the updated values 
-[ ] edit the old entry array to the new entry object array, whether for a singular card or a range of cards 
-[ ] once submitted, this will redirect you back to the card database that will allow you to add 
-[] viewswap will be needed to redirect back to the database form
