### ISSUE TITLE
Feature: User can Delete cards in their deck

### ISSUE THREAD

**Issue by edc061598** [edc061598/front-end-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Within your card deck page, have a delete button that is shown in the figma 
- [ ] Have an event listener for your card deck, which would be an unordered list 
- [ ] Create a confirmation modal that displays after you hit the delete button 
- [ ] if the user clicks cancel, hide the modal 
- [ ] if the user confirms the delete button: 
 -[] it will delete all cards from local storage 
-[ ] YOU HAVE NOW FINISHED THE FRONT END PROJECT!!!
